config/routes.rb
CheerHighlights::Application.routes.draw do

  get "skills/index"

  get "skills/edit"

  get "skills/new"

  get "skills/show"

  get "microposts/show"

  get "microposts/index"

  get "microposts/edit"

  get "microposts/new"

  

  root :to => 'user#index', :as => "root"

  devise_for :users , :skip => 'invitation'

  resources :users
  get "user/_profile", :as => "profile"

  resources :media
  resources :microposts
  resources :skills

  

  

end

app/models/media.rb
class Media < ActiveRecord::Base
  attr_accessible :pic
  attr_accessible :microposts

  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates :pic, :attachment_presence => true
  validates_with AttachmentPresenceValidator, :attributes => :pic

  belongs_to :user
  has_many :microposts

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content

  attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  

  belongs_to :user
  validates :content, :presence => true

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :comment, :rating, :skill

  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :firstname, :lastname, :skilllevel, :skills
  attr_accessible :microposts
  attr_accessible :pic

  has_many :media
  has_many :microposts, dependent: :destroy
  has_many :skills
  

  
  validates_email :email
  validates :email, :uniqueness => true
  validates :password, :presence => true
  validates :password, :length => { :in => 5..15, :message => " needs to be between 5 and 15 characters" } 
  validates :firstname, :presence => true
  validates :lastname, :presence => true


 
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  before_filter :authenticate_user!
  
  
  def index
    @media = Media.all
  end

  def new
    @media = Media.new
  end

  #def display_img
    #@img = Media.find(params[:media])
    #send_data(@img.img, :type => @img.filetype, :filename => @img.filename,
              #:disposition => 'inline')
  #end

  def show
    @media = Media.find(params[:media])
    @microposts = @media.microposts.paginate(page: params[:page])
  end


  def create
    @media = Media.create(params[:media])
  end


    #respond_to do |format|
      #if @media.save
        #format.html { redirect_to @media, notice: 'Media was successfully created.' }
        #format.json { render json: @media, status: :created, location: @media }
      #else
        #format.html { render action: "new" }
        #format.json { render json: @media.errors, status: :unprocessable_entity }
      #end
    #end


end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def show
    @micropost = Micropost.find(params[:id])
 
    @microposts = Micropost.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
     end
  end


  def index
    @microposts = Micropost.all
 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def new
    @microposts = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  def create
    @micropost = Micropost.new( params[:micropost] )
    if @micropost.save
      render "show"
    else
      render "new"
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id]) 
    @micropost.destroy
    redirect_to new_micropost_path
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  
  def show
    @skills = Skill.find(params[:id])
 
    @skills = Skill.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill }
     end
  end


  def index
    @skills = Skill.all
 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skills }
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def new
    @skills = Skill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill }
    end
  end

  def create
    @skill = Skill.new( params[:skill] )
    if @skill.save
      render "show"
    else
      render "new"
    end
  end

  def destroy
    @skill = Skill.find(params[:id]) 
    @skill.destroy
    redirect_to new_skill_path
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:id])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:user])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:user])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end

  def create
    @user = User.create( params[:user] )
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_helper.rb
module MediaHelper
   
end

app/helpers/microposts_controller_helper.rb
module MicropostsControllerHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheerHighlights</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Cheer Highlights</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  
    <script src="http://code.jquery.com/jquery.js"></script>

</head>
<body>


 


<%= yield %>

</body>
</html>

app/views/media/_microposts.html.erb
<%= form_for(@micropost) do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "New comment..." %>
  </div>
  <%= f.submit "Post" %>
<% end %>

<%= @microposts.each do |micropost| %>
<li>
  <p class="comment_body">"<%= micropost.body %>"</p>
  <br/>
  <p class="comment_info"><%= micropost.name %> - <%= time_ago_in_words(comment.created_at) %> ago </p>
</li>
<% end %>


<ul class="microposts">
  <% if @post.microposts.empty? %>
    <li>none yet</li>
  <% else %>
    <%= render 'microposts' %>
  <% end %>
</ul>



<li>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
</li>

app/views/media/_productreviews.html.erb
<!-- <ul>
  <% @reviews.each do |review| %>
    <li>
        Product: <%= review.book.title %><br>
        Author: <%= review.book.author %><br>
        User:   <%= review.user.first_name %><br>
        Review: <%= review.content %>
    </li>
  <% end %>
</ul> -->

app/views/media/create.html.erb
<body class="profile">

 <%= render "shared/menu" %>

 <div class="photospage">


<div class= "photoslogo">
 <img src= "<%= asset_path( 'photoslogo.png' ) %>"> 
</div>


<%= form_for @media, :url => media_path, :html => { :multipart => true } do |form| %>
  <%= hidden_field_tag(:user_id, current_user.id) %>
  <%= form.file_field :pic %>
 <p class="button"><%= form.submit "POST" %></p>


 <% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>  
<% else %>

    <%= link_to "Sign up now!", user_path %>
  </div>
<% end %>

 <%= image_tag @media.pic.url(:medium) %>


<% end %>

</div>
</body>

 

app/views/media/edit.html.erb
<%= form_for @media, :url => media_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :pic %>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/media/index.html.erb
<body class="profile">

 <%= render "shared/menu" %>

 <div class="photospage">


<div class= "photoslogo">
 <img src= "<%= asset_path( 'photoslogo.png' ) %>"> 
</div>


<%= form_for @media, :url => media_path, :html => { :multipart => true } do |form| %>
  <%= hidden_field_tag(:user_id, current_user.id) %>
  <%= form.file_field :pic %>
 <p class="button"><%= form.submit "POST" %></p>


 <% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>  
<% else %>

    <%= link_to "Sign up now!", user_path %>
  </div>
<% end %>

 <%= image_tag @media.pic.url(:medium) %>


<% end %>

</div>
</body>
 

app/views/media/show.html.erb
<h1>Media#show</h1>

<%= image_tag @media.pic.url %>
<%= image_tag @media.pic.url(:medium) %>
<%= image_tag @media.pic.url(:thumb) %>


<%= render 'microposts' %>



      

app/views/microposts/edit.html.erb
<%= form_for @micropost, :url => microposts_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>

app/views/microposts/index.html.erb
<body class="profile">

<div class= "photoslogo">
 <img src= "<%= asset_path( 'photoslogo.png' ) %>"> 
</div>


<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= image_tag @microposts.pic.url(:medium) %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>


<br />

<%= link_to 'Add New Photo', new_micropost_path %>

</body>

app/views/microposts/new.html.erb
<%= render "shared/menu" %>

<body class="profile">

<div class= "photoslogo">
 <img src= "<%= asset_path( 'photoslogo.png' ) %>"> 
</div>

<div class="newmicropost">
<%= form_for @microposts, :html => { :multipart => true } do |f| %>
  <div><%= f.file_field :avatar %>
      <%= f.text_area :content, placeholder: "New comment..." %> 
  </div>

  <% if @microposts.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @microposts.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="button">
    <%= f.submit "Create Post" %>
  </div>
</div>
<% end %>

app/views/microposts/show.html.erb
<%= render "shared/menu" %>


<body class="profile">

<div class= "photoslogo">
 <img src= "<%= asset_path( 'photoslogo.png' ) %>"> 
</div>


<%= @micropost.content %>
  <%= image_tag @micropost.avatar.url(:medium) %>

  <%= link_to "Delete", micropost_path(@micropost.id), :method => :delete, title: @micropost.content %>
  <%= link_to "New", micropost_path(@micropost.id), :method => :new, title: @micropost.content %>
<%# end %>

app/views/shared/_menu.html.erb
<div class="menu">
    <ul>
      <li> <%= link_to "Home", root_path %> </li>
      <li> <%= link_to "Photos", new_micropost_path %> </li>
      <li> <a href="pages/page2.html">Videos</a></li>
      <li> <%= link_to "My Profile", skills_path %> </li>
    </ul>
</div>

app/views/skills/_profile.html.erb
<body class="profile">
  <%= render "shared/menu" %>
  
  <div class="profilemiddle">
  <% if user_signed_in? %>
  <h1>Hi, <%= current_user.firstname %>!</h1>
<% end %>

<body>


<div class="myskills">
<h1>My Skills</h1>

<div class="tumbling">
<h2>Tumbling</h2>
<hr>

<%= link_to 'Add New Skill', new_skill_path %>

<br>

<div class= "skillstable">
<% @skills.each do |skill| %>
  <ul><tr>
    <li><td><%= skill.skill %> <%= link_to 'Edit', edit_skill_path(skill) %> <%= link_to 'Delete', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td></li>
  </tr></ul>
<% end %>
</table>
</div>


</div>

<div class="stunting">
  <h2>Stunting</h2>
  <hr>

  <%= link_to 'Add New Skill', new_skill_path %>

  <br>

  <div class= "skillstable">
    <% @skills.each do |skill| %>
      <ul><tr>
        <li><td><%= skill.skill %> 
      <%= link_to 'Edit', edit_skill_path(skill) %> 
      <%= link_to 'Delete', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td></li>
      </tr></ul>
  <% end %>
  </table>
  </div>


</div>

</div>

<div class="myfeed">
<h1>My Feed</h1>
<p> Congrats, you've recently added these skills: 

  <% @skills.each do |skill| %>
  <ul>
    <li><%= skill.skill %></li>
  </ul>
</p>
  <% end %>

</div>

</body>


</body>

app/views/skills/_skillform.html.erb
<div>
  <h2>My Skills</h2>
  <ul>
  <%= @skills.content %>
    <li>
        Skill: <%= skill.user.skill %><br>
        Rating: <%= skill.user.rating %><br>
        Comments: <%= skill.comments %><br>
    </li>
  </ul>

     <p>
      <%=f.label :skills %><br />
      <%=f.text_field :skills %>
    </p>
    <p>
      <%=f.label :rating %><br />
      <%=f.text_field :rating %>
    </p>
    <p>
      <%=f.label :comments %><br />
      <%=f.text_field :comments %>
    </p>

    <p class="button"><%= f.submit %></p>

</div>

app/views/skills/edit.html.erb
<h1>Skills#edit</h1>
<p>Find me in app/views/skills/edit.html.erb</p>

app/views/skills/index.html.erb
<body class="profile">

<div class= "profilelogo">
 <img src= "<%= asset_path( 'profilelogo.png' ) %>"> 
</div>

<%= render 'profile' %>


<br />


</body>

app/views/skills/new.html.erb
<%= render "shared/menu" %>

<body class="profile">

<div class= "profilelogo">
 <img src= "<%= asset_path( 'profilelogo.png' ) %>"> 
</div>

<%= form_for @skills, :html => { :multipart => true } do |f| %>
  <div class="newskill">
    <%= f.text_field :skill, placeholder: "New skill..." %> 
    <div class="button">
      <%= f.submit "Add Skill" %>
    </div>
  </div>
<% end %>

<ul>

app/views/skills/show.html.erb
<%= render "shared/menu" %>


<body class="profile">

<div class= "profilelogo">
 <img src= "<%= asset_path( 'profilelogo.png' ) %>"> 
</div>

<%= @skill.skill %>

  <%= link_to "Delete", skill_path, :method => :delete, title: @skill.skill %>
  <%= link_to "New", new_skill_path, :method => :new, title: @skill.skill %>

app/views/user/_form.html.erb
<div class="form">
  <h1>Sign Up</h1>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class ="error_messages">
        <h2>Form is Invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

     <p>
      <%=f.label :firstname %><br />
      <%=f.text_field :firstname %>
    </p>
    <p>
      <%=f.label :lastname %><br />
      <%=f.text_field :lastname %>
    </p>
    <p>
      <%=f.label :email %><br />
      <%=f.text_field :email %>
    </p>
    <p>
      <%=f.label :password %><br />
      <%=f.password_field :password %>
    </p>
    <p>
      <%=f.label :password_confirmation %><br />
      <%=f.password_field :password_confirmation %>
    </p>

    <p class="button"><%= f.submit %></p> 
  <% end %>
</div>

app/views/user/_signin_form.html.erb
<div class="login">
  <img src="<%= asset_path( 'cheerlogo2.png' ) %>"> 
  <p>Cheer Highlights is a community where you can share and vote on your favorite cheerleading videos, photos, and product reviews!</p>
  <div id="login-content"> 
    <% unless user_signed_in? %> 
      <%= form_for("user", :url => user_session_path) do |f| %> 
        <%= f.label :username %> <br/> 
        <%= f.text_field :username , :size=>'15',:maxlength=>'32' %> <br/> 
        <%= f.label :password %> <br/> 
        <%= f.password_field :password , :size=>'15', :maxlength=>'32' %> 
        <br/>
        <br />
        <div class="button"> 
        <%= f.submit "Sign in" %> <br />
        </div>
  </div>
         <br /> 
        <%= link_to "Forgot your password?", new_password_path('user')  %>
        <p class="signup"> <%= link_to "Sign-Up", users_path%> </p>
      <% end %> 
    <% end %>
    <% if user_signed_in? %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% end %> 
 
</div>

app/views/user/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/user/index.html.erb
<%= render "shared/menu" %>

<body>

  <div class="menusymbol">
    <a href="#">&#9776</a>
  </div>

  <div class="middle">
    <%= render 'signin_form' %>
  </div>


    



            <!-- <div id="myCarousel" class="carousel slide">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
  <!-- Carousel items -->
            <!--<div class="carousel-inner">
                <div class="active item"><img src="img/sliderimage1.png"></div>
                <div class="item"><img src="img/sliderimage2.png"></div>
                <div class="item"><img src="img/sliderimage3.png"></div>
            </div>
  <!-- Carousel nav -->
            <!--<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
            </div> -->


  <div class="bottom">    
   
    <div class="ribbon"><div class="ribbon-stitches-top"></div><strong class="ribbon-content"><h1>How It Works</h1></strong><div class="ribbon-stitches-bottom"></div></div>
       

      <div class="info">

        <div class="paragraph1">
          <img src= "<%= asset_path( 'videosicon.png' ) %>"> <p>Post cheerleading Youtube videos and vote on your favorites!</p>
        </div>

        <div class="paragraph2">
          <img src="<%= asset_path( 'photosicon.png' ) %>"> <p>Upload cheerleading photos of yourself, your friends, or your favorite teams! Users can vote and comment on the best photos.</p>
        </div>

        <div class="paragraph3">
          <img src="<%= asset_path( 'producticon.png' ) %>"> <p>Read and write product reviews about the items you use for cheerleading.</p>
        </div>

        <div class="paragraph4">
          <img src="<%= asset_path( 'profileicon.png' ) %>"> <p> Make a profile that keeps track of your skill progression as well as your top picture, video, and product review selections.</p>
        </div>

      </div>

    </div>
</div>

         
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
       

    </body>

app/views/user/new.html.erb
<h1>New user</h1>


<%= render 'form' %>

app/views/user/show.html.erb
<p id="notice"><%= notice %></p>